### ISSUE TITLE
Error during flair collapse:  keyerror

### ISSUE THREAD

**Issue by wolfgangrumpf** [BrooksLabUCSC/flair#102]
I ran flair collapse and it quit after the first pass (single-exon genes?) - it mapped for quite a while, then threw this exception:  

`"""
Traceback (most recent call last):
  File "/opt/python/3.7.3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/python/3.7.3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/gpfs0/home/gdlauberlab/rwr002/TESTING/flair/bin/count_sam_transcripts.py", line 84, in count_transcripts_for_reads
    isoform_read[t] += [r]
KeyError: 'ENST00000379378.8_ENSG00000205250.9'`

The output also said:  Entry name must contain underscore-delimited transcriptid and geneid like so:	 ENST00000318842.11_ENSG00000156313.12 or a4bab8a3-1d28_chr8:232000

There was an empty collapse.isoforms.gtf in the directory, so I actually have two questions:

1.  Why did this key error occur?  I looked through my input gtf and that string wasn't found
2. Since I only saw flair mention single-exon genes, does that mean it didn't find the multi-exon genes?

**Comment by wolfgangrumpf** [comment]
my gtf reference file does contain several entries similar to this:  

chr16	HAVANA	transcript	67192155	67198918	.	+	.	gene_id "ENSG00000205250.9"; transcript_id "ENST00000379378.8"; gene_type "protein_coding"; gene_name "E2F4"; transcript_type "protein_coding"; transcript_name "E2F4-201"; level 2; protein_id "ENSP00000368686.3"; transcript_support_level "1"; hgnc_id "HGNC:3118"; tag "non_canonical_conserved"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; ccdsid "CCDS32464.1"; havana_gene "OTTHUMG00000172975.3"; havana_transcript "OTTHUMT00000421565.2";

**Comment by wolfgangrumpf** [comment]
Newer ensemble hg38 (build 99) fixed this one
