### ISSUE TITLE
Flair collapse - rm: cannot remove `flair.collapse.firstpass.q.counts': No such file or directory

### ISSUE THREAD

**Issue by wolfgangrumpf** [BrooksLabUCSC/flair#105]
I reported an issue yesterday (102) where flair collapse failed with a key error.  I tried running the same thing today *without* the gtf file input and it gave me a completely different error.  

Here's the command I ran:  

`python flair.py collapse --threads 45 -g /gpfs0/home/gdlauberlab/lab/databases/isoseq/genomes/hg38.fa  -r ccs.fastq --generate_map -q flair_all_corrected.bed`

And here's the error:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/python/3.7.3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/python/3.7.3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/gpfs0/home/gdlauberlab/rwr002/TESTING/flair/bin/count_sam_transcripts.py", line 84, in count_transcripts_for_reads
    isoform_read[t] += [r]
KeyError: 'm64034_200216_143134/3016532/ccs;16'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs0/home/gdlauberlab/rwr002/TESTING/flair/bin/count_sam_transcripts.py", line 238, in <module>
    counts = p.map(count_transcripts_for_reads, grouped_reads)
  File "/opt/python/3.7.3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/python/3.7.3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'm64034_200216_143134/3016532/ccs;16'
usage: script.py countsfile1 countsfile2 [...] outfilename
Filtering isoforms by read coverage
usage: script.py countsfile psl_to_append_counts min_read_threshold outfilename
usage: script.py psl|bed genome.fa outfilename
Removing intermediate files/done
rm: cannot remove `flair.collapse.firstpass.q.counts': No such file or directory
```

**Comment by wolfgangrumpf** [comment]
I had to remove --generate_map to get this to run
