### ISSUE TITLE
flair collapse cannot allocate memory

### ISSUE THREAD

**Issue by sdws1983** [BrooksLabUCSC/flair#107]
Hi!

I run flair-collapse for isoform assembly by concatenating corrected read psl files together with following commands:
```
python flair.py collapse -f /data/jinlab/reference/B73_AGPv4/Zea_mays.B73_RefGen_v4.43.gtf -m ~/software/minimap2-2.17_x64-linux/minimap2 -t 72 --temp_dir ./ -o combined_all_corrected -r /data/jinlab/ymhuang/data/nanopore/X837-* -q combined_all_corrected.psl -g /data/jinlab/reference/B73_AGPv4/Zea_mays.AGPv4.dna.toplevel.fa
```

The log:
```
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Filtering isoforms
Renaming isoforms
Aligning reads to first-pass isoform reference
[M::mm_idx_gen::15.156*1.62] collected minimizers
[M::mm_idx_gen::16.589*2.37] sorted minimizers
[M::main::16.643*2.37] loaded/built the index for 245594 target sequence(s)
[M::mm_mapopt_update::17.170*2.33] mid_occ = 288
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 245594
[M::mm_idx_stat::17.522*2.30] distinct minimizers: 13989458 (41.65% are singletons); average occurrences: 5.575; average spacing: 5.404
[M::worker_pipeline::71.729*41.86] mapped 448810 sequences
[M::worker_pipeline::95.885*46.76] mapped 447427 sequences
[M::worker_pipeline::128.258*53.21] mapped 446344 sequences
[M::worker_pipeline::150.309*53.72] mapped 449613 sequences
[M::worker_pipeline::183.704*57.18] mapped 446788 sequences
[M::worker_pipeline::208.218*57.80] mapped 447437 sequences
[M::worker_pipeline::238.783*59.30] mapped 449576 sequences
[M::worker_pipeline::263.843*59.68] mapped 448366 sequences
[M::worker_pipeline::294.353*61.02] mapped 447101 sequences
[M::worker_pipeline::318.499*61.15] mapped 446842 sequences
[M::worker_pipeline::350.151*62.20] mapped 447072 sequences
[M::worker_pipeline::373.073*62.04] mapped 446470 sequences
[M::worker_pipeline::404.936*62.89] mapped 447868 sequences
[M::worker_pipeline::429.051*62.89] mapped 447770 sequences
[M::worker_pipeline::460.041*63.57] mapped 450432 sequences
[M::worker_pipeline::483.449*63.44] mapped 446512 sequences
[M::worker_pipeline::516.509*64.04] mapped 448890 sequences
[M::worker_pipeline::539.613*63.78] mapped 448042 sequences
[M::worker_pipeline::572.292*64.30] mapped 450910 sequences
[M::worker_pipeline::595.141*64.14] mapped 446353 sequences
[M::worker_pipeline::627.514*64.49] mapped 447620 sequences
[M::worker_pipeline::632.899*63.95] mapped 241625 sequences
[M::worker_pipeline::686.676*63.31] mapped 444875 sequences
[M::worker_pipeline::712.230*63.33] mapped 450202 sequences
[M::worker_pipeline::744.647*63.74] mapped 445199 sequences
[M::worker_pipeline::768.529*63.61] mapped 444369 sequences
[M::worker_pipeline::801.740*63.99] mapped 443890 sequences
[M::worker_pipeline::826.858*63.93] mapped 445405 sequences
[M::worker_pipeline::859.245*64.26] mapped 443576 sequences
[M::worker_pipeline::882.880*64.14] mapped 443614 sequences
[M::worker_pipeline::916.026*64.45] mapped 446455 sequences
[M::worker_pipeline::940.943*64.39] mapped 445181 sequences
[M::worker_pipeline::972.982*64.66] mapped 444706 sequences
[M::worker_pipeline::996.959*64.59] mapped 445327 sequences
[M::worker_pipeline::1029.798*64.85] mapped 443928 sequences
[M::worker_pipeline::1054.623*64.83] mapped 447173 sequences
[M::worker_pipeline::1085.799*65.03] mapped 448384 sequences
[M::worker_pipeline::1111.957*65.03] mapped 444775 sequences
[M::worker_pipeline::1143.738*65.24] mapped 444367 sequences
[M::worker_pipeline::1168.018*65.16] mapped 445627 sequences
[M::worker_pipeline::1200.748*65.37] mapped 444326 sequences
[M::worker_pipeline::1224.705*65.28] mapped 444465 sequences
[M::worker_pipeline::1253.347*65.07] mapped 444185 sequences
[M::worker_pipeline::1255.225*64.97] mapped 70181 sequences
[M::worker_pipeline::1308.360*64.59] mapped 533418 sequences
[M::worker_pipeline::1330.281*64.43] mapped 533587 sequences
[M::worker_pipeline::1363.868*64.64] mapped 535853 sequences
[M::worker_pipeline::1385.776*64.50] mapped 534063 sequences
[M::worker_pipeline::1420.200*64.70] mapped 536290 sequences
[M::worker_pipeline::1440.849*64.52] mapped 532794 sequences
[M::worker_pipeline::1475.313*64.71] mapped 532425 sequences
[M::worker_pipeline::1498.493*64.58] mapped 533645 sequences
[M::worker_pipeline::1530.546*64.73] mapped 532578 sequences
[M::worker_pipeline::1553.307*64.62] mapped 533681 sequences
[M::worker_pipeline::1586.293*64.78] mapped 533595 sequences
[M::worker_pipeline::1608.816*64.66] mapped 532038 sequences
[M::worker_pipeline::1641.463*64.79] mapped 533317 sequences
[M::worker_pipeline::1664.135*64.71] mapped 534455 sequences
[M::worker_pipeline::1696.581*64.86] mapped 532432 sequences
[M::worker_pipeline::1719.466*64.78] mapped 535551 sequences
[M::worker_pipeline::1751.686*64.93] mapped 534142 sequences
[M::worker_pipeline::1760.346*64.68] mapped 385192 sequences
[M::worker_pipeline::1814.627*64.42] mapped 476154 sequences
[M::worker_pipeline::1836.772*64.30] mapped 473620 sequences
[M::worker_pipeline::1870.860*64.46] mapped 474000 sequences
[M::worker_pipeline::1892.165*64.34] mapped 472983 sequences
[M::worker_pipeline::1927.209*64.49] mapped 475538 sequences
[M::worker_pipeline::1949.812*64.38] mapped 474382 sequences
[M::worker_pipeline::1984.076*64.53] mapped 475240 sequences
[M::worker_pipeline::2005.518*64.40] mapped 476406 sequences
[M::worker_pipeline::2040.487*64.54] mapped 475011 sequences
[M::worker_pipeline::2062.580*64.44] mapped 475803 sequences
[M::worker_pipeline::2096.852*64.58] mapped 474290 sequences
[M::worker_pipeline::2118.795*64.47] mapped 472602 sequences
[M::worker_pipeline::2153.067*64.61] mapped 477685 sequences
[M::worker_pipeline::2171.966*64.36] mapped 472524 sequences
[M::worker_pipeline::2172.524*64.34] mapped 13886 sequences
[M::worker_pipeline::2226.430*64.09] mapped 450875 sequences
[M::worker_pipeline::2248.041*64.01] mapped 453120 sequences
[M::worker_pipeline::2281.495*64.14] mapped 453470 sequences
[M::worker_pipeline::2302.170*64.02] mapped 448120 sequences
[M::worker_pipeline::2336.944*64.15] mapped 449046 sequences
[M::worker_pipeline::2358.235*64.06] mapped 451735 sequences
[M::worker_pipeline::2391.521*64.18] mapped 450148 sequences
[M::worker_pipeline::2412.589*64.08] mapped 452226 sequences
[M::worker_pipeline::2445.788*64.20] mapped 452069 sequences
[M::worker_pipeline::2467.778*64.11] mapped 451343 sequences
[M::worker_pipeline::2500.653*64.23] mapped 451970 sequences
[M::worker_pipeline::2522.246*64.14] mapped 451274 sequences
[M::worker_pipeline::2554.916*64.25] mapped 456060 sequences
[M::worker_pipeline::2575.881*64.17] mapped 450663 sequences
[M::worker_pipeline::2603.625*63.98] mapped 449684 sequences
[M::worker_pipeline::2656.840*63.81] mapped 449234 sequences
[M::worker_pipeline::2678.943*63.75] mapped 451151 sequences
[M::worker_pipeline::2712.311*63.86] mapped 451472 sequences
[M::worker_pipeline::2734.444*63.80] mapped 446883 sequences
[M::worker_pipeline::2767.547*63.91] mapped 450076 sequences
[M::worker_pipeline::2789.599*63.83] mapped 445108 sequences
[M::worker_pipeline::2822.598*63.93] mapped 447569 sequences
[M::worker_pipeline::2845.439*63.86] mapped 446169 sequences
[M::worker_pipeline::2877.562*63.95] mapped 448420 sequences
[M::worker_pipeline::2899.984*63.91] mapped 449594 sequences
[M::worker_pipeline::2932.498*64.01] mapped 450509 sequences
[M::worker_pipeline::2955.478*63.96] mapped 450669 sequences
[M::worker_pipeline::2988.445*64.06] mapped 447913 sequences
[M::worker_pipeline::3004.023*63.88] mapped 416625 sequences
[M::worker_pipeline::3058.293*63.75] mapped 436136 sequences
[M::worker_pipeline::3082.759*63.73] mapped 434119 sequences
[M::worker_pipeline::3114.895*63.81] mapped 435203 sequences
[M::worker_pipeline::3137.974*63.78] mapped 440004 sequences
[M::worker_pipeline::3172.531*63.88] mapped 435658 sequences
[M::worker_pipeline::3195.308*63.83] mapped 433063 sequences
[M::worker_pipeline::3228.780*63.92] mapped 438581 sequences
[M::worker_pipeline::3252.715*63.89] mapped 435080 sequences
[M::worker_pipeline::3285.567*63.98] mapped 434661 sequences
[M::worker_pipeline::3309.583*63.95] mapped 438289 sequences
[M::worker_pipeline::3342.894*64.04] mapped 435245 sequences
[M::worker_pipeline::3366.189*64.01] mapped 433174 sequences
[M::worker_pipeline::3391.969*63.87] mapped 419993 sequences
[M::worker_pipeline::3449.285*63.70] mapped 439298 sequences
[M::worker_pipeline::3472.322*63.67] mapped 439928 sequences
[M::worker_pipeline::3506.729*63.76] mapped 440568 sequences
[M::worker_pipeline::3529.843*63.73] mapped 441733 sequences
[M::worker_pipeline::3563.539*63.82] mapped 440141 sequences
[M::worker_pipeline::3588.512*63.80] mapped 442799 sequences
[M::worker_pipeline::3621.196*63.89] mapped 443362 sequences
[M::worker_pipeline::3645.671*63.86] mapped 443211 sequences
[M::worker_pipeline::3678.997*63.94] mapped 442197 sequences
[M::worker_pipeline::3702.353*63.91] mapped 440501 sequences
[M::worker_pipeline::3736.907*63.99] mapped 441870 sequences
[M::worker_pipeline::3760.556*63.95] mapped 441147 sequences
[M::worker_pipeline::3793.630*64.03] mapped 438727 sequences
[M::worker_pipeline::3815.196*63.92] mapped 441169 sequences
[M::worker_pipeline::3816.304*63.91] mapped 39877 sequences
[M::worker_pipeline::3872.354*63.76] mapped 444529 sequences
[M::worker_pipeline::3896.410*63.74] mapped 445638 sequences
[M::worker_pipeline::3929.602*63.81] mapped 449010 sequences
[M::worker_pipeline::3954.207*63.79] mapped 443176 sequences
[M::worker_pipeline::3987.654*63.86] mapped 445770 sequences
[M::worker_pipeline::4010.390*63.83] mapped 446041 sequences
[M::worker_pipeline::4045.205*63.90] mapped 445348 sequences
[M::worker_pipeline::4068.452*63.88] mapped 445703 sequences
[M::worker_pipeline::4102.438*63.95] mapped 441138 sequences
[M::worker_pipeline::4126.473*63.92] mapped 444925 sequences
[M::worker_pipeline::4159.258*63.99] mapped 447663 sequences
[M::worker_pipeline::4184.542*63.98] mapped 444336 sequences
[M::worker_pipeline::4217.015*64.05] mapped 442468 sequences
[M::worker_pipeline::4239.576*64.01] mapped 447081 sequences
[M::worker_pipeline::4243.429*63.96] mapped 132273 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: /home/jinlab/software/minimap2-2.17_x64-linux/minimap2 -a -t 72 -N 4 combined_all_corrected.firstpass.fa /data/jinlab/ymhuang/data/nanopore/X837-01-z /data/jinlab/ymhuang/data/nanopore/X837-N01_clean.fastq.gz /data/jinlab/ymhuang/data/nanopore/X837-N02_clean.fastq.gz /data/jinlab/ymhuang/datan.fastq.gz /data/jinlab/ymhuang/data/nanopore/X837-N06_clean.fastq.gz
[M::main] Real time: 4243.907 sec; CPU: 271390.520 sec; Peak RSS: 9.135 GB
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 326, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 230, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

It seems the memory is not enough when running minimap2 (system shows that the Mem and Swap are full), how should I do for this issue?

**Comment by belgravia** [comment]
So I have been working on a way to make flair much more memory efficient. I think implementing this will not go as fast as I would like, so you may not want to wait for this. Thanks for your patience thus far.

For this issue, I have the following suggestions for when running flair-collapse:
A) You could take a subset of all of your reads to supply as `-r`
B) You could run each of your fastq's through separate flair-collapse runs, and then use cuffmerge to merge the final isoform.gtf output
C) If you are ok with running tools/scripts, you can try the following to manually run flair-collapse:

1) Align each your sample to the firstpass isoforms, obtain counts for each isoform, and then remove the bulky sam files. Repeat for each sample file.  
>  minimap2 -a -t {number of threads} -N 4 combined_all_corrected.firstpass.fa reads1.fastq > reads1.sam
> samtools view -q 1 -h -S reads1.sam > reads1.q1.sam
> python bin/count_sam_transcripts.py -s reads1.q1.sam -o countsfile1.txt
> rm reads1.sam reads1.q1.sam

2) Combine the count files. The last argument for this command is your output file name.
> python bin/combine_counts.py countsfile1.txt countsfile2.txt ... combined_counts.txt
3) Obtain final isoforms
> python bin/match_counts.py combined_counts.txt combined_all_corrected.firstpass.bed 3 combined_all_corrected.isoforms.bed

You can then convert the isoforms.bed file to a gtf or to the isoform sequence using scripts in the bin/. 
 
Sorry there isn't a great solution for this yet.
-Alison

**Comment by sdws1983** [comment]
Hi Allison,

I ran flair collapse manually with the scripts you mentioned aboved, and it worked well.

Thanks a lot!

**Comment by jamlover** [comment]
Hi. I ran into the same issue with memory so took on of the paths you suggested above:
"B) You could run each of your fastq's through separate flair-collapse runs, and then use cuffmerge to merge the final isoform.gtf output"

So I now have 14,157 collapsed gtf files, one for each sequence file I have. I installed cufflinks and then as a test I tried to merge 6 of my collapsed gtf files just to see if it would work. I got the following error from cuffmerge:

[Tue Feb 16 08:55:46 2021] Beginning transcriptome assembly merge
-------------------------------------------

[Tue Feb 16 08:55:46 2021] Preparing output location cuffmerge_output/
Traceback (most recent call last):
  File "/data/jmartins/progs/cufflinks/cuffmerge", line 580, in <module>
    sys.exit(main())
  File "/data/jmartins/progs/cufflinks/cuffmerge", line 538, in main
    gtf_input_files = test_input_files(transfrag_list_file)
  File "/data/jmartins/progs/cufflinks/cuffmerge", line 268, in test_input_files
    g = open(line,"r")
IOError: [Errno 2] No such file or directory: 'scaf30\tFLAIR\ttranscript\t511124\t512928\t.\t-\t.\tgene_id "FMg014931"; transcript_id "FMt028417";'

Having never used cufflinks/cuffmerge I am at a disadvantage, but I don't understand why it would look at the first line in the first gtf file provided to it for merging and say that there is no file or directory matching that line (which is what it is doing). I know this is not really a flair issue at this point, but since it took me about two weeks to get all of the gtf output from collapse generated, I am hoping that perhaps you have some idea what I can do to get cuffmerge to work, or if not, if you have an alternative suggestion as to how I can merge my 14,157 collapsed gtf files.

Thanks,
John Martinson

**Comment by jamlover** [comment]
I think I figured it out. I needed to provide cuffmerge with a file with the list of gtf files to be merged rather than actually including all the files to me merged on command line. My bad.  Leaving this message here in case it might help anyone else who ever runs into the same issue.
