### ISSUE TITLE
Error at flair-collapse step

### ISSUE THREAD

**Issue by gm-nyc** [BrooksLabUCSC/flair#111]
Hi, I am trying to run flair on some long read data and am running in to this error at the collapse step

'Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Process ForkPoolWorker-5:
Traceback (most recent call last):
  File "/miniconda3/envs/flair_env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/miniconda3/envs/flair_env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/miniconda3/envs/flair_env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/miniconda3/envs/flair_env/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/envs/flair_env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/miniconda3/envs/flair_env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/miniconda3/envs/flair_env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/miniconda3/envs/flair_env/lib/python3.6/multiprocessing/queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "/miniconda3/envs/flair_env/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
OverflowError: cannot serialize a string larger than 4GiB'

For reference, I'm running this with 600gb of memory. Thanks for your help!

**Comment by belgravia** [comment]
Do you know approximately how large your dataset is? The size or number of lines of your *all_corrected.bed would be helpful. Could you also send me the command you're using here?

I did some googling about this problem and wasn't able to find anything too applicable for this issue. This error _might_ have to do with how large your file is. In the past, I've seen the multiprocessing module use too much RAM but that gave a more straightforward error message, so I'm not really sure about this one.

-Alison

**Comment by gm-nyc** [comment]
Hi Allison,

Thanks for your help. The file is pretty large. I merged 3 samples as the instructions recommend and the combined .psl file is ~20GB, 30,215,005 lines. I re-ran this step using python 3.8 and it seems to be working (it's been running for ~20hours and no error given yet, at least). Does this help in understanding the source of the problem?

**Comment by gm-nyc** [comment]
Wanted to update you: I re-ran this using python 3.8 and did not see this error. Looks like the file size was the issue using python 2.7. Thanks for your help!
