### ISSUE TITLE
Error in diffExp

### ISSUE THREAD

**Issue by shamsbhuiyan** [BrooksLabUCSC/flair#131]
Hi I was wondering if you had any experience with this specific runtime error when running DiffExp:

```
running DESEQ2 dge
/home/sbhuiyan/flair-dec09/flair/bin/runDE.py:109: FutureWarning: read_table is deprecated, use read_csv instead.
  quantDF  = pd.read_table(matrix, header=0, sep='\t', index_col=0)
/space/scratch/SHaMSpipe_out/mouseBrainAndLiver/analysis/minION/brain/env/lib/python2.7/site-packages/rpy2/robjects/lib/ggplot2.py:67: UserWarning: This was designed againt ggplot2 version 2.1.0 but you have 3.3.2
  warnings.warn('This was designed againt ggplot2 version %s but you have %s' % (TARGET_VERSION, ggplot2.__version__))
Traceback (most recent call last):
  File "/home/sbhuiyan/flair-dec09/flair/bin/runDE.py", line 218, in <module>
    main()
  File "/home/sbhuiyan/flair-dec09/flair/bin/runDE.py", line 138, in main
    R('dds <- DESeq(dds)')
  File "/space/scratch/SHaMSpipe_out/mouseBrainAndLiver/analysis/minION/brain/env/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 362, in __call__
    res = self.eval(p)
  File "/space/scratch/SHaMSpipe_out/mouseBrainAndLiver/analysis/minION/brain/env/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/space/scratch/SHaMSpipe_out/mouseBrainAndLiver/analysis/minION/brain/env/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in lfproc(x, y, weights = weights, cens = cens, base = base, geth = geth,  :
  newsplit: out of vertex space

running DESEQ2 die
/home/sbhuiyan/flair-dec09/flair/bin/runDE.py:109: FutureWarning: read_table is deprecated, use read_csv instead.
  quantDF  = pd.read_table(matrix, header=0, sep='\t', index_col=0)
/space/scratch/SHaMSpipe_out/mouseBrainAndLiver/analysis/minION/brain/env/lib/python2.7/site-packages/rpy2/robjects/lib/ggplot2.py:67: UserWarning: This was designed againt ggplot2 version 2.1.0 but you have 3.3.2
  warnings.warn('This was designed againt ggplot2 version %s but you have %s' % (TARGET_VERSION, ggplot2.__version__))
Traceback (most recent call last):
  File "/home/sbhuiyan/flair-dec09/flair/bin/runDE.py", line 218, in <module>
    main()
  File "/home/sbhuiyan/flair-dec09/flair/bin/runDE.py", line 146, in main
    vsd    = R('vst(dds,blind=FALSE)')
  File "/space/scratch/SHaMSpipe_out/mouseBrainAndLiver/analysis/minION/brain/env/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 362, in __call__
    res = self.eval(p)
  File "/space/scratch/SHaMSpipe_out/mouseBrainAndLiver/analysis/minION/brain/env/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/space/scratch/SHaMSpipe_out/mouseBrainAndLiver/analysis/minION/brain/env/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in vst(dds, blind = FALSE) : less than 'nsub' rows,
  it is recommended to use varianceStabilizingTransformation directly

running DRIMSEQ diu
/space/scratch/SHaMSpipe_out/mouseBrainAndLiver/analysis/minION/brain/env/lib/python2.7/site-packages/rpy2/robjects/lib/ggplot2.py:67: UserWarning: This was designed againt ggplot2 version 2.1.0 but you have 3.3.2
  warnings.warn('This was designed againt ggplot2 version %s but you have %s' % (TARGET_VERSION, ggplot2.__version__))
/home/sbhuiyan/flair-dec09/flair/bin/runDU.py:115: FutureWarning: read_table is deprecated, use read_csv instead.
  quantDF  = pd.read_table(matrix, header=0, sep='\t', index_col=0)
```

Please let me know if you would like me to provide my input counts_matrix.tsv file. Here is a sample of the first few lines:

```
ids     sample3_occipital_batch1        sample4_parietal_batch1 sample7_occipital_batch1        sample8_parietal_batch1 sample11_occipital_batch1     sample12_parietal_batch1
009a6bc5-0ec9-4837-af34-5c4b2c2ab728_Basecall_2D_2d_chr12:2448000       0.0     0.0     0.0     0.0     3.0     0.0
02562edb-8a89-4744-9d60-01de41ead05b_Basecall_2D_2d_chr12:2448000       5.0     1.0     2.0     0.0     1.0     1.0
037a8a57-4aa0-4a0e-9f6d-819bc0cd3e9d_Basecall_2D_chr12:2448000  4.0     7.0     8.0     1.0     6.0     4.0
03be5f1a-0540-4ba3-88cd-1acec1064781_Basecall_2D_chr12:2053000  5.0     14.0    5.0     4.0     6.0     11.0
050c138c-a049-4c65-bedc-9a111ffc6b39_Basecall_2D_2d_chr12:2053000       9.0     42.0    8.0     2.0     17.0    54.0
0795dba6-66c5-4c28-8b09-372f52d89612_Basecall_2D_chr12:2448000  0.0     0.0     0.0     0.0     0.0     0.0
07d5837d-1deb-470b-81bc-0cc4ff18866f_Basecall_2D_chr12:2448000  0.0     0.0     0.0     0.0     0.0     0.0
087891ca-455d-4fa0-96e2-5bf53ec35c90_Basecall_2D_chr12:2448000  0.0     2.0     1.0     0.0     1.0     1.0
095c8229-9401-4bc8-9df5-79adfc837fb4_Basecall_2D_chr12:2448000  0.0     0.0     1.0     0.0     0.0     0.0
```

**Comment by Jeltje** [comment]
Is this still an issue with the latest version of Flair?

If so, could you try running Flair from its docker container:

`docker pull brookslab/flair:latest`

You can then run flair commands like so
``docker run -v `pwd`:/mydata -w /mydata brookslab/flair:latest flair diffExp (...)``

(note that you no longer need the .py extension after flair)

If this solves your problem to your satisfaction, please close this ticket.

We are working to make Flair conda installable but this might take a while.
