### ISSUE TITLE
Error on Collapse command

### ISSUE THREAD

**Issue by RichardCorbett** [BrooksLabUCSC/flair#138]
Hi there,
I am processing a lane of promethion data with flair.  This is my first run so please let me know if I'm doing something silly.  

```
#download and convert the docker container to singularity
singularity pull docker://quay.io/brookslab/flair

#alignment
singularity exec -B /projects/alignment_references/9606/hg38_no_alt/genome/fasta/ -B input/  ./flair_latest.sif python3 /usr/local/flair/flair.py align --g hg38_no_alt.fa -r PAF25672.fastq -t 96

#correct using a reference GTF file
singularity exec -B /projects/alignment_references/9606/hg38_no_alt/genome/fasta/ -B input/  ./flair_latest.sif python3 /usr/local/flair/flair.py correct -t 96 -q flair.aligned.bed -g hg38_no_alt.fa -f hg38.ncbiRefSeq.gtf -c hg38_no_alt.fa.fai

#collapse into consensus transcripts 
singularity exec -B /projects/alignment_references/9606/hg38_no_alt/genome/fasta/ -B ../Aeron/input/  ./flair_latest.sif python3 /usr/local/flair/flair.py collapse -t 96 -r PAF25672.fastq -g hg38_no_alt.fa -f hg38.ncbiRefSeq.gtf  -q flair_all_corrected.bed
```

The collapse command ran for 8 days and then crashed with this message:
```
Annotated ends extracted from GTF
Read data extracted


Single-exon genes grouped, collapsing
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/flair/bin/collapse_isoforms_precise.py", line 290, in run_se_collapse
    edited_line = edit_line(list(line), tss, tes, tes-tss)
  File "/usr/local/flair/bin/collapse_isoforms_precise.py", line 424, in edit_line
    line[18] = str(blocksize) + ','
IndexError: list assignment index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/flair/bin/collapse_isoforms_precise.py", line 547, in <module>
    res = p.map(run_se_collapse, chrom_names)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
IndexError: list assignment index out of range
```

Do you see anything I should do differently? I do not have any short reads available for this sample.

**Comment by Jeltje** [comment]
Sorry about that, the docker image was really old. We have since fixed the `index out of range` bug, could you please try again?

You can get the most recent docker image from hub.docker.com using
`docker pull brookslab/flair:1.6.1`

If this does not solve your issue, please reopen this ticket.
