### ISSUE TITLE
memory allocation error during flair collapse

### ISSUE THREAD

**Issue by callumparr** [BrooksLabUCSC/flair#149]
I run this with qsub 

```
python flair-1.5/flair.py collapse -r Mouse_aging/RawData/*.fastq -q flair_all_corrected.psl -g cDNA_DESeq2/ReferenceData/Mus_musculus.GRCm38.dna.primary_assembly.fa -s salmon-latest_linux_x86_64/bin/salmon -f cDNA_DESeq2/ReferenceData/Mus_musculus.GRCm38.99.gtf -m minimap2/minimap2 --keep_intermediate --temp_dir /home/scratch/callum/ --trust_ends
```

this generates flair.collapse.firstpass.fa/psl, and flair.collapse.firstpass.unfiltered.psl then throws this error. 

```
Traceback (most recent call last):
  File "/home/callum/flair-1.5/bin/count_sam_transcripts.py", line 237, in <module>
    p = Pool(args.t)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by Jeltje** [comment]
[Today's commit](https://github.com/BrooksLabUCSC/flair/commit/04c42bd96c91c926d9ab20faea292709bd5c5e04) hopefully deals with that problem. 

You can get this version using  `git clone git@github.com:BrooksLabUCSC/flair.git`, we hope to do a new release soon.

Please reopen this ticket if you still experience problems.
