### ISSUE TITLE
NameError: name 'tqdm' is not defined in ssCorrect.py

### ISSUE THREAD

**Issue by shaniAmare** [BrooksLabUCSC/flair#152]
Hi @belgravia, 

I managed to run flair once previously. But now I get the following error when I'm trying to run the latest version of flair on my data. The align step works but the correction part gives a `NameError `as below.

```
[M::mm_idx_gen::109.603*1.61] collected minimizers
[M::mm_idx_gen::125.000*2.26] sorted minimizers
[M::main::125.003*2.26] loaded/built the index for 195 target sequence(s)
[M::mm_mapopt_update::130.053*2.21] mid_occ = 762
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 195
[M::mm_idx_stat::132.341*2.19] distinct minimizers: 168242330 (35.56% are singletons); average occurrences: 6.015; average spacing: 3.074; total length: 3110318602
[M::worker_pipeline::634.139*6.61] mapped 127689 sequences
[M::worker_pipeline::1115.628*7.19] mapped 128945 sequences
[M::worker_pipeline::1591.849*7.42] mapped 128965 sequences
[M::worker_pipeline::1731.066*7.46] mapped 42028 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: /stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/minimap2/minimap2 -ax splice -t 8 --secondary=no /stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/genome_rnasequin_decoychr_2.4.fa /stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/ccs_fastq/S3R_m64087_200413_100303.ccs.fastq.gz
[M::main] Real time: 1731.338 sec; CPU: 12910.321 sec; Peak RSS: 21.256 GB
Samtools version >= 1.3 detected
Traceback (most recent call last):
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/Nanopore/flair/flair/bin/ssCorrect.py", line 425, in <module>
    main()
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/Nanopore/flair/flair/bin/ssCorrect.py", line 340, in main
    if gtf != None: juncs, chromosomes, knownSS = gtfToSSBed(gtf, knownSS)
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/Nanopore/flair/flair/bin/ssCorrect.py", line 245, in gtfToSSBed
    for exonInfo in tqdm(txnList, total=len(txnList), desc="Step 1/5: Splitting junctions from GTF by chromosome", dynamic_ncols=True, position=1) if verbose else txnList:
NameError: name 'tqdm' is not defined
Correction command did not exit with success status
[M::mm_idx_gen::103.959*1.62] collected minimizers
[M::mm_idx_gen::119.487*2.30] sorted minimizers
[M::main::119.488*2.30] loaded/built the index for 195 target sequence(s)
[M::mm_mapopt_update::124.369*2.25] mid_occ = 762
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 195
[M::mm_idx_stat::127.052*2.22] distinct minimizers: 168242330 (35.56% are singletons); average occurrences: 6.015; average spacing: 3.074; total length: 3110318602
[M::worker_pipeline::620.773*6.64] mapped 152645 sequences
[M::worker_pipeline::1072.206*7.20] mapped 155673 sequences
[M::worker_pipeline::1519.145*7.42] mapped 153732 sequences
[M::worker_pipeline::1580.735*7.44] mapped 25291 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: /stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/minimap2/minimap2 -ax splice -t 8 --secondary=no /stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/genome_rnasequin_decoychr_2.4.fa /stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/ccs_fastq/S4R_m64087_200413_100303.ccs.fastq.gz
[M::main] Real time: 1581.131 sec; CPU: 11766.077 sec; Peak RSS: 21.068 GB
Samtools version >= 1.3 detected
Traceback (most recent call last):
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/Nanopore/flair/flair/bin/ssCorrect.py", line 425, in <module>
    main()
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/Nanopore/flair/flair/bin/ssCorrect.py", line 340, in main
    if gtf != None: juncs, chromosomes, knownSS = gtfToSSBed(gtf, knownSS)
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/Nanopore/flair/flair/bin/ssCorrect.py", line 245, in gtfToSSBed
    for exonInfo in tqdm(txnList, total=len(txnList), desc="Step 1/5: Splitting junctions from GTF by chromosome", dynamic_ncols=True, position=1) if verbose else txnList:
NameError: name 'tqdm' is not defined
Correction command did not exit with success status
```
Have this issue come before, and if so, what was the solution? I looked around the repo and in Google but could not figure out exactly how to fix it. I'm running it on a slurm workload manager. Happy to provide more details if needed.

Really appreciate your feedback.

Many thanks in advance.
Shani.

**Comment by Jeltje** [comment]
Hi Shani, 

Do you still have this issue with either the latest releases (1.5.0 or 1.5.1) or the current master branch?
If so I would like to follow up.

If not, could you please close this ticket? 
Thanks.

**Comment by Jeltje** [comment]
Please reopen if you still have this issue.
