### ISSUE TITLE
predictProductivity.py Error: cannot construct subsequence with negative offset or length < 1

### ISSUE THREAD

**Issue by zoucheng123** [BrooksLabUCSC/flair#173]
Hi, I got an error stated as below when I ran predictProductivity.py.

Traceback (most recent call last):
  File "/home/zhuofeng/zoucheng/software/flair-master/bin/predictProductivity.py", line 372, in <module>
    main()
  File "/home/zhuofeng/zoucheng/software/flair-master/bin/predictProductivity.py", line 337, in main
    isoformObjs = getSeqs(bed, genome)
  File "/home/zhuofeng/zoucheng/software/flair-master/bin/predictProductivity.py", line 156, in getSeqs
    bt.sequence(fi=genome, tab=True, s=True, split=True, name=True)
  File "/public/software/anaconda3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/public/software/anaconda3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 401, in wrapped
    decode_output=decode_output,
  File "/public/software/anaconda3/lib/python3.7/site-packages/pybedtools/helpers.py", line 455, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools getfasta -tab -split -s -name -fo /tmp/pybedtools.r8x1vh3q.tmp -fi /home/data/reference/human_genome/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa -bed /home/zhuofeng/zoucheng/my_data/nanopore_PCa/in_home_analysis/flair/03_collapse/merged_7_samples/merged_7_samples.isoforms.bed

**Error message was:
Error: cannot construct subsequence with negative offset or length < 1**

And here is the command I used:
command_dir=/home/zhuofeng/zoucheng/software/flair-master/bin
gtf=/home/data/reference/human_genome/ensembl/Homo_sapiens.GRCh38.98.gtf
fasta=/home/data/reference/human_genome/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa

**python ${command_dir}/predictProductivity.py -i ./merged_7_samples.isoforms.bed -g ${gtf} -f ${fasta} --longestORF > productivity.bed**

I've checked that my "merged_7_samples.isoforms.bed" is not empty. Could you please help me with this problem？Thank you in advance.

**Comment by Jeltje** [comment]
Is this still a problem with the latest predictProductivity (see my comment in #155 )?
If so, I would love to have a look. Could you please let me know your bedtools version and attach a few lines of your input bed file (after verifying it gives the error)?

**Comment by Jeltje** [comment]
Pleae reopen this ticket if you are still having issues.
