### ISSUE TITLE
Flair.py collapse error - NameError: name 'res' is not defined 

### ISSUE THREAD

**Issue by andy941** [BrooksLabUCSC/flair#174]
Hi,
I have an issue with Flair v1.5 at the collapse step. 

Here is my command:
```
flair.py collapse --gtf Araport11_GTF_genes_transposons.Mar202021.gtf \
-g TAIR10_Chr.all.fa -r [space separated fastq files] -q flair_all_corrected.psl
```
Here is the error:
``` 
Annotated ends extracted from GTF
Read data extracted
Annotated ends extracted from GTF
Annotated ends extracted from GTF
Read data extracted
Read data extracted
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/frankwellmer/miniconda3/envs/bio/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/frankwellmer/miniconda3/envs/bio/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/frankwellmer/miniconda3/envs/bio/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/frankwellmer/miniconda3/envs/bio/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/frankwellmer/miniconda3/envs/bio/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/frankwellmer/miniconda3/envs/bio/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/frankwellmer/miniconda3/envs/bio/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/frankwellmer/miniconda3/envs/bio/bin/bin/collapse_isoforms_precise.py", line 666, in <module>
    for r in res:  # combine results
NameError: name 'res' is not defined 
```
The program doesn't stop but keeps looping and giving the same error indefinitely.
I tried to use .bed and .psl files and I checked that the formatting of the input files is correct (Chromosomes naming etc.).
Could it be a bug in the program?

Thank you very much,
Andrea

**Comment by belgravia** [comment]
Hi Andrea,

It looks almost like you're running FLAIR by somehow splitting the run into multiple processes. The 'Annotated ends extracted from GTF' and 'Read data extracted' lines are only supposed to be printed once and it is only after the information is read into the script that FLAIR will use multiprocessing. It's unclear to me why they would be printed three times.

I'm unfamiliar with this kind of thing happening. I'm not sure if this has something to do with the machine you're working on or if it might be something to do with your environment. Sorry this isn't much help, but have you tried running flair in the flair conda environment? And could you tell me what version of the python multiprocessing package you have, so that I can try to replicate this error? 

-Alison

**Comment by andy941** [comment]
Hi Alison,
Thank you very much for looking into this.
I am running it in a conda environment already (python.3.9). Which python multiprocessing package does flair depend on? As a sanity check I just update the whole environment but the problem persists. Here is my conda environment if that can be of any help:

```
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py39h9ed2024_1003
ca-certificates           2021.7.5             hecd8cb5_1
certifi                   2021.5.30        py39hecd8cb5_0
cffi                      1.14.6           py39h2125817_0
chardet                   4.0.0           py39hecd8cb5_1003
conda                     4.10.3           py39hecd8cb5_0
conda-package-handling    1.7.3            py39h9ed2024_1
cryptography              3.4.7            py39h2fd3fbb_0
idna                      2.10               pyhd3eb1b0_0
libcxx                    10.0.0                        1
libffi                    3.3                  hb1e8313_2
ncurses                   6.2                  h0a44026_1
openssl                   1.1.1k               h9ed2024_0
pip                       21.1.3           py39hecd8cb5_0
pycosat                   0.6.3            py39h9ed2024_0
pycparser                 2.20                       py_2
pyopenssl                 20.0.1             pyhd3eb1b0_1
pysocks                   1.7.1            py39hecd8cb5_0
python                    3.9.5                h88f2d9e_3
python.app                3                py39h9ed2024_0
readline                  8.1                  h9ed2024_0
requests                  2.25.1             pyhd3eb1b0_0
ruamel_yaml               0.15.100         py39h9ed2024_0
setuptools                52.0.0           py39hecd8cb5_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               hce871da_0
tk                        8.6.10               hb0a8c7a_0
tqdm                      4.61.2             pyhd3eb1b0_1
tzdata                    2021a                h52ac0ba_0
urllib3                   1.26.6             pyhd3eb1b0_1
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h1de35cc_0
yaml                      0.2.5                haf1e3a3_0
zlib                      1.2.11               h1de35cc_3
```
Here you can have a look at the formatting of the annotation and genome assemblies I'm using (I work with Arabidopsis):
**Annotation**
```
$ head -n 20 Araport11_GTF_genes_transposons.Mar202021.gtf
Chr1    Araport11       gene    3631    5899    .       +       .       transcript_id "AT1G01010"; gene_id "AT1G01010";
Chr1    Araport11       mRNA    3631    5899    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       five_prime_UTR  3631    3759    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    3631    3913    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       CDS     3760    3913    .       +       0       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       protein 3760    5630    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    3996    4276    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       CDS     3996    4276    .       +       2       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    4486    4605    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       CDS     4486    4605    .       +       0       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    4706    5095    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       CDS     4706    5095    .       +       0       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    5174    5326    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       CDS     5174    5326    .       +       0       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       CDS     5439    5630    .       +       0       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    5439    5899    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       three_prime_UTR 5631    5899    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       gene    6788    9130    .       -       .       transcript_id "AT1G01020"; gene_id "AT1G01020";
Chr1    Araport11       mRNA    6788    8737    .       -       .       transcript_id "AT1G01020.2"; gene_id "AT1G01020";
Chr1    Araport11       mRNA    6788    8737    .       -       .       transcript_id "AT1G01020.6"; gene_id "AT1G01020";
```
**Assembly**
```
$ head TAIR10_Chr.all.fa
>Chr1 CHROMOSOME dumped from ADB: Jun/20/09 14:53; last updated: 2009-02-02
CCCTAAACCCTAAACCCTAAACCCTAAACCTCTGAATCCTTAATCCCTAAATCCCTAAATCTTTAAATCCTACATCCAT
GAATCCCTAAATACCTAATTCCCTAAACCCGAAACCGGTTTCTCTGGTTGAAAATCATTGTGTATATAATGATAATTTT
ATCGTTTTTATGTAATTGCTTATTGTTGTGTGTAGATTTTTTAAAAATATCATTTGAGGTCAATACAAATCCTATTTCT
```

Let me know if I can be of any help.
Andrea

**Comment by andy941** [comment]
I will try to run it in the conda environment provided in the repository as well as soon as possible. Sorry I misread the answer at first.

**Comment by MikeLippincott** [comment]
Hello!

Tagging Participants: @andy941 @belgravia 

I was having the same issue as Andrea. Reproduced the issue after 
```conda update --all```. Also experinced issue on some(I tried a couple but not all versions between 3.8 and 3.10.5) 
python versions > 3.7. After ``conda install python=3.7`` the issue went away for me. Must be an incompatibility with 
the newer muliprocessing module in the newer python versions? Hopefully this works?  

Here is my conda environment if it helps:
```
# Name                    Version                   Build  Channel
bedtools                  2.30.0               h0e31d98_3    bioconda
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.6.15            h033912b_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cython                    0.29.30          py37hc568d09_0    conda-forge
dill                      0.3.5.1            pyhd8ed1ab_0    conda-forge
htslib                    1.15.1               hc057d7f_0    bioconda
k8                        0.2.5                h6151dfb_2    bioconda
kerneltree                0.0.5            py37h819e570_1    bioconda
krb5                      1.19.3               hb49756b_0    conda-forge
libblas                   3.9.0           15_osx64_openblas    conda-forge
libcblas                  3.9.0           15_osx64_openblas    conda-forge
libcurl                   7.83.1               h372c54d_0    conda-forge
libcxx                    14.0.5               hce7ea42_1    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           15_osx64_openblas    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libzlib                   1.2.12               hfe4f2af_1    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
minimap2                  2.24                 h1f540d2_1    bioconda
multiprocess              0.70.13          py37h994c40b_1    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
numpy                     1.21.6           py37h345d48f_0    conda-forge
openssl                   1.1.1p               hfe4f2af_0    conda-forge
pandas                    1.3.4            py37h5b83a90_1    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
pybedtools                0.9.0            py37h18d0eb1_1    bioconda
pysam                     0.19.1           py37h64e44a1_0    bioconda
python                    3.7.13               hdfd78df_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
samtools                  1.15.1               h9f30945_0    bioconda
setuptools                59.8.0           py37hf985489_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.5               hd9f0692_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.12               hfe4f2af_1    conda-forge

```

-Mike
