### ISSUE TITLE
Flair align fails with pysam libcrypto.so.1.0.0 not found

### ISSUE THREAD

**Issue by vpeddu** [BrooksLabUCSC/flair#242]
**Copy and paste the exact command you tried to run**

Run command: 
``` flair align --mm_index hs1.mmi -r in.fastq.gz -t 64 --nvrna -o out.flair_align```
**How did you install Flair?**
`conda create -n flair -c conda-forge -c bioconda flair`

**What happened?**
```
[WARNING] Indexing parameters (-k, -w or -H) overridden by parameters used in the prebuilt index.
[M::main::10.336*1.00] loaded/built the index for 25 target sequence(s)
[M::mm_mapopt_update::12.683*1.00] mid_occ = 892
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 25
[M::mm_idx_stat::13.773*1.00] distinct minimizers: 100277218 (38.70% are singletons); average occurrences: 5.856; average spacing: 5.308; total length: 3117292070
[M::worker_pipeline::73.962*37.82] mapped 378877 sequences
[M::worker_pipeline::85.409*37.91] mapped 158252 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -ax splice --secondary=no -uf -k14 -t 64 /private/groups/kimlab/vikas/refs/hs1.mmi /private/groups/kimlab/vikas/sree/hs1/01_02_18_R94_KRASKO_iPSC.fastq.gz
[M::main] Real time: 86.809 sec; CPU: 3239.415 sec; Peak RSS: 27.767 GB
Traceback (most recent call last):
  File "/private/groups/kimlab/vikas/sree/drna_flair/flair/src/flair/bam2Bed12.py", line 22, in <module>
    from samJuncs import SAM
  File "/private/groups/kimlab/vikas/miniconda/envs/flair/lib/python3.8/site-packages/flair/samJuncs.py", line 23, in <module>
    import pysam
  File "/private/groups/kimlab/vikas/miniconda/envs/flair/lib/python3.8/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "flair/flair.py", line 1097, in <module>
    main()
  File "flair/flair.py", line 1015, in main
    status = align()
  File "flair/flair.py", line 98, in align
    subprocess.check_call(bed_conversion_cmd, stdout=open(args.o+'.bed', 'w'))
  File "/private/groups/kimlab/vikas/miniconda/envs/flair/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/private/groups/kimlab/vikas/miniconda/envs/flair/bin/python3', '/private/groups/kimlab/vikas/sree/drna_flair/flair/src/flair/bam2Bed12.py', '-i', 'KRASKO.flai_align.bam']' returned non-zero exit status 1.
```
We know it's ugly but we promise it helps us solve problems faster.

**What else do we need to know?**
It seems like this is an issue stemming from the conda pysam install. Would it be possible to update the pysam versions in the conda recipe?

**Comment by icemduru** [comment]
is libssl1.0.0 installed on your computer. If not, you can try:

`sudo apt install libssl1.0.0`

**Comment by Jeltje** [comment]
@vpeddu please respond to this ticket. The solution by @icemduru should work for you. If it does, please close this ticket. Thanks.
