### ISSUE TITLE
diffsplice_fishers_exact error when dealing with ir.events.quant.tsv

### ISSUE THREAD

**Issue by 1255207453** [BrooksLabUCSC/flair#250]
Hi,
When I ran diffsplice_fishers_exact, it showed the following error message:
Traceback (most recent call last):
  File "/home/wcy_z3/miniconda3/envs/mamba/bin/diffsplice_fishers_exact", line 48, in <module>
    writer.writerow(line + [sps.fisher_exact(events[feature]['counts'])[1]])
  File "/home/wcy_z3/miniconda3/envs/mamba/lib/python3.8/site-packages/scipy/stats/_stats_py.py", line 4668, in fisher_exact
    raise ValueError("The input `table` must be of shape (2, 2).")
ValueError: The input `table` must be of shape (2, 2).

This error only occurs when dealing with ir.events.quant.tsv
A short one of  ir.events.quant.tsv is shown below:
feature_id      coordinate      Col_ck_batch1   hda9_ck_batch1  isoform_ids
inclusion_1:7232-7383   1:7232-7383     2.0     2.0     93:1577|06b1316b-feb2-48c0-8fae-64040833699f_AT1G01020
exclusion_1:7232-7383   1:7232-7383     44.0    62.0    AT1G01020.1_AT1G01020,94:1343|1f967829-0fc5-4de6-ba56-14e529ae085a_AT1G01020,AT1G01020.5_AT1G01020,95:1030|c82ba5e5-4d13-4cf8-8ae6-d4c04e447318_AT1G01020,102:1355|18d89b23-46c5-423b-a9c6-bc36437ebdd3_AT1G01020,86:1037|bdfbe9c7-9e76-45b0-a6a9-36b9982c7b7c_AT1G01020,AT1G01020.4_AT1G01020,AT1G01020.3_AT1G01020,84:1039|9a0956ce-ed81-490d-9349-05d5c43ae68c_AT1G01020,93:1355|ae30d10c-576c-4bdd-a96d-a58458dafb75_AT1G01020,81:1150|b30428d0-e071-4371-aafa-d2cb6815739e_AT1G01020,103:1134|476dc00e-4d4b-4164-939a-b1f9174f9dd7_AT1G01020,98:1537|35e453e7-29e9-45f6-b625-fd8b493ac5de_AT1G01020,98:784|d9f3b827-2458-43a2-8db2-dbb00c0da16a_AT1G01020,98:683|dec11fe9-e894-43ca-9c9d-87ff9a3aae91_AT1G01020

My version is flair 1.7.0 and I install It using mamba，the code is : mamba install -c bioconda flair=1.7

I found it is a bug that should be already solved, here's the link https://github.com/BrooksLabUCSC/flair/issues/95. but it still occurs to me. I think the latest vesion forgets the bug.

Thanks,
Qing

**Comment by Jeltje** [comment]
I'm looking into this, it's a very weird issue because there are no commits with related changes to the program.

**Comment by Jeltje** [comment]
We're thinking this might be a different issue but I can't reproduce it with just those two lines. Would you mind either pasting all the lines of a test file where you see the problem, or sending me one at jeltje.van.baren@gmail.com?

**Comment by QingCheZhang** [comment]
Hello, I found the reason for the error is that the sorted ir.events.quant.tsv file contains events with the same site names, such as "2:9217299-9217387"
```
inclusion_2:9217299-9217387     2:9217299-9217387       13.0    10.0    9.0     9.0     97:2031|1447e86b-c487-49f9-804c-3d27f7a20aec_AT2G21520  0.134540614421088       [[15.0,11.0],[68.0,102.0]]
exclusion_2:9217299-9217387     2:9217299-9217387       63.0    94.0    78.0    65.0    AT2G21520.3_AT2G21520,AT2G21520.1_AT2G21520,94:2613|07fb27ad-6f48-48d2-8171-7a9cd39f1d60_AT2G21520       0.134540614421088       [[15.0,11.0],[68.0,102.0]]
inclusion_2:9217299-9217387     2:9217299-9217387       2.0     1.0     1.0     1.0     102:1331|bac1e692-2d55-4243-929b-1ad56d034fbc_AT2G21520 0.134540614421088       [[15.0,11.0],[68.0,102.0]]
exclusion_2:9217299-9217387     2:9217299-9217387       5.0     8.0     5.0     4.0     104:1956|a6a18031-aac4-4df9-a921-efa627284f71_AT2G21520,104:1817|d5136e02-8e32-4ddc-85f4-38804d02f478_AT2G21520,104:1796|41a8b26d-1868-4406-8c1e-f3965f8a0168_AT2G21520,79:1675|bad1fe10-b34f-4ec4-bf4d-65b7f5ab20e6_AT2G21520   0.134540614421088       [[15.0,11.0],[68.0,102.0]]]
```
I don’t know why this error occurred, but I corrected it by modifying diffsplice_fishers_exact. Below is my code:```
#!/home/wcy_z3/miniconda3/envs/flair-1.7/bin/python

import sys
import csv
import os
import scipy.stats as sps

try:
    events_quant = open(sys.argv[1])
    colname1 = sys.argv[2]
    colname2 = sys.argv[3]
    outfilename = sys.argv[4]
except:
    print('usage: diffsplice_fishers_exact events.quant.tsv colname1 colname2 out.fishers.tsv')
    sys.exit()

header = events_quant.readline().rstrip().split('\t')

if colname1 in header:
    col1 = header.index(colname1)
else:
    sys.stderr.write('Could not find {} in {}\n'.format(colname1, ' '.join(header)))
    sys.exit(1)

if colname2 in header:
    col2 = header.index(colname2)
else:
    sys.stderr.write('Could not find {} in {}\n'.format(colname2, ' '.join(header)))
    sys.exit(1)

events = {}
for line in events_quant:
    line = line.rstrip().split('\t')
    feature = line[0][line[0].find('_')+1:]
    if feature not in events:
        events[feature] = {}
        events[feature]['entries'] = []
        events[feature]['counts'] = {'inclusion': [], 'exclusion': []}
    events[feature]['entries'].append(line)
    if 'inclusion' in line[0]:
        events[feature]['counts']['inclusion'].append([float(line[col1]), float(line[col2])])
    elif 'exclusion' in line[0]:
        events[feature]['counts']['exclusion'].append([float(line[col1]), float(line[col2])])

def generate_2x2_matrix(counts):
    inclusion_col1 = sum([entry[0] for entry in counts['inclusion']])
    inclusion_col2 = sum([entry[1] for entry in counts['inclusion']])
    exclusion_col1 = sum([entry[0] for entry in counts['exclusion']])
    exclusion_col2 = sum([entry[1] for entry in counts['exclusion']])
    return [[inclusion_col1, inclusion_col2], [exclusion_col1, exclusion_col2]]

features_sorted = sorted(events.keys())
with open(outfilename, 'wt') as outfile:
    writer = csv.writer(outfile, delimiter='\t', lineterminator=os.linesep)
    writer.writerow(header + [colname1 + '-' + colname2 + '_pval', '2x2_matrix'])
    for feature in features_sorted:
        matrix = generate_2x2_matrix(events[feature]['counts'])
        if all(len(row) == 2 for row in matrix) and len(matrix) == 2:
            pval = sps.fisher_exact(matrix)[1]
        else:
            sys.stderr.write('Invalid 2x2 matrix for feature {}: {}\n'.format(feature, matrix))
            pval = 'NA'
        for line in events[feature]['entries']:
            matrix_str = str(matrix).replace(' ', '')
            writer.writerow(line + [pval, matrix_str])
```
This code generated the results above. Can you tell me why the same event site is produced?
