### ISSUE TITLE
ssUtils.py gtfToSSBed crashes if gtf doesn't have transcript_id

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#291]
The attached bogus GTF (really a GFF from gffread) causes flair to crash because it doesn't check for a failed re match and report an error.

```
+ nice python ../../flair/flair.py correct --query GL000218.1-flair.aligned.bed --genome GL000218.1-genome.fa --gtf GL000218.1-annotation.gtf --shortread GL000218.1-introns.bed --threads 32 --print_check
Starting correct...
Traceback (most recent call last):
  File "/hive/users/markd/projs/silvia/projs/flair/filtering/refactor_SRsupport/debug/../../flair/flair.py", line 86, in <module>
    main()
  File "/hive/users/markd/projs/silvia/projs/flair/filtering/refactor_SRsupport/debug/../../flair/flair.py", line 41, in main
    corrected_reads = correct()
  File "/hive/users/markd/projs/silvia/projs/flair/filtering/flair-refactor/src/flair/flair_correct.py", line 90, in correct
    juncs, chromosomes, knownSS = gtfToSSBed(args.gtf, knownSS, printErr, printErrFname, verbose)
  File "/hive/users/markd/projs/silvia/projs/flair/filtering/flair-refactor/src/flair/ssUtils.py", line 138, in gtfToSSBed
    txn = re.search('transcript_id "([^\"]+)"', l).group(1)#
AttributeError: 'NoneType' object has no attribute 'group'
```
[GL000218.1-annotation.gtf.gz](https://github.com/BrooksLabUCSC/flair/files/12543141/GL000218.1-annotation.gtf.gz)

**Comment by diekhans** [comment]
p.s. chatGPT finds this bug
