### ISSUE TITLE
diffSplice : No such file or directory: 'call_diffsplice_events.py'

### ISSUE THREAD

**Issue by CorentinAube** [BrooksLabUCSC/flair#309]
**Copy and paste the exact command you tried to run**
python3 flair_diffSplice.py -i flair.collapse.isoforms.bed -q flair.quantify.counts.tsv -o test

**How did you install Flair?**
1. bioconda (e.g. `conda create -n flair -c conda-forge -c bioconda flair`)

**What happened?**

```
Traceback (most recent call last):
  File "/mnt/d/Corentin/projet_RNAViZer/FLAIR/HSV1/flair_diffSplice.py", line 130, in <module>
    diffSplice()
  File "/mnt/d/Corentin/projet_RNAViZer/FLAIR/HSV1/flair_diffSplice.py", line 86, in diffSplice
    subprocess.check_call(['call_diffsplice_events.py', args.i, filebase, args.q])
  File "/home/corentin/miniconda3/envs/flair/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/corentin/miniconda3/envs/flair/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/corentin/miniconda3/envs/flair/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/corentin/miniconda3/envs/flair/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'call_diffsplice_events.py'```

**What else do we need to know?**

Hello,
 
I installed flair with conda and it's worked well. Now, I would like to use diffSplice module that is not included with Flair. I downloaded flair_diffSplice.py and  call_diffsplice_events.py. These two files are in the same folder. When I run diffSplice, this error message and I don't know what can I do.

Thank you for your help,
Corentin

**Comment by Jeltje** [comment]
The directory that contains flair_diffSplice.py does not look like a conda environment tree structure. If you install Flair using conda it should end up in something like
`/home/yourusername/miniconda3/envs/flair/lib/python3.10/site-packages/flair/flair_diffSplice.py`
where `lib/python3.10/site-packages` is in your $PATH.

Is call_diffsplice_events.py present in `/mnt/d/Corentin/projet_RNAViZer/FLAIR/HSV1/` ?
