### ISSUE TITLE
flair correct - FileNotFound %s_inconsistent.bed 

### ISSUE THREAD

**Issue by sguizard** [BrooksLabUCSC/flair#353]
**Copy and paste the exact command you tried to run**
```
flair correct \
  -q ERR10859992.bed \
  -j data/shortreads_SJ.out.tab \
  -g data/Ovis_aries_rambouillet.ARS-UI_Ramb_v2.0.dna.toplevel.fa \
  --output results/ERR10859992 \
  --threads 8 \
  --nvrna
```

**How did you install Flair?**
`conda create -n flair -c conda-forge -c bioconda flair`

**What happened?**

```
Step 3/5: Preparing annotated junctions to use for correction: 100%|██████████| 68/68 [00:01<00:00, 51.09it/s] 
Step 4/5: Preparing reads for correction: 3127900it [00:05, 571086.43it/s]████| 68/68 [00:01<00:00, 120.60it/s]
Step 5/5: Correcting Splice Sites: 100%|██████████| 46/46 [00:01<00:00, 28.55it/s]
Traceback (most recent call last):  89%|████████▉ | 41/46 [00:01<00:00, 31.68it/s]
  File "/exports/cmvm/eddie/eb/groups/alaw3_grp/sguizard/Softwares/miniforge3/envs/flair/lib/python3.8/site-packages/flair/ssCorrect.py", line 423, in <module>
    main()
  File "/exports/cmvm/eddie/eb/groups/alaw3_grp/sguizard/Softwares/miniforge3/envs/flair/lib/python3.8/site-packages/flair/ssCorrect.py", line 402, in main
    with open(os.path.join(tempDir, "%s_inconsistent.bed" % chrom),'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/cmvm/eddie/eb/groups/clark_grp2/R_BFX_Flair_project_WorkingDirectory/04_flair_correct/ed475636-ef90-40a9-b5c2-6ffd478c10be/1_inconsistent.bed'
Correction command did not exit with success status:
/exports/cmvm/eddie/eb/groups/alaw3_grp/sguizard/Softwares/miniforge3/envs/flair/bin/python /exports/cmvm/eddie/eb/groups/alaw3_grp/sguizard/Softwares/miniforge3/envs/flair/lib/python3.8/site-packages/flair/ssCorrect.py -i data/ERR10859992.bed -w 15 -p 8 -o results/ERR10859992 --progress -f data/Ovis_aries_rambouillet.ARS-UI_Ramb_v2.0.dna.toplevel.fa -j data/shortreads_SJ.out.tab
```
We know it's ugly but we promise it helps us solve problems faster.

**What else do we need to know?**
This error is similar/same as issues #207 #134 #336 #352 #26.
I have checked the consistency of sequences names between the input bed file, the junctions file and the genome. 
I can provide the input files if needed. 
Thanks in advance for assistance with this issue.

**Comment by sguizard** [comment]
I found a workaround to get flair to work. 
I created a new conda environment (flair2). 
With conda, installed bedtools, samtools, minimap2 and gcc. 
With pip, I installed flair-brookslab and pipettor. 
Then clone the repo and run the flair.py script from the cloned code with the flair2 env activated. 

I hope it helps. 

```
><(((^> conda create -n flair2
><(((^> conda install samtools minimap2 bedtools gcc # dependencies found on the readthedoc, gcc needed for flair-brookslab 
><(((^> pip install flair-brookslab
><(((^> pip install pipettor
><(((^> git clone https://github.com/BrooksLabUCSC/flair.git
><(((^> cd flair
><(((^> ln -s ../04_flair_correct/data/Ovis_aries_rambouillet.ARS-UI_Ramb_v2.0.dna.toplevel.fa
><(((^> ln -s ../04_flair_correct/data/shortreads_SJ.out.tab
><(((^> ln -s ../04_flair_correct/data/ERR10859992.bed
><(((^> ./flair.py correct \
  -q ERR10859992.bed \
  -j shortreads_SJ.out.tab \
  -g Ovis_aries_rambouillet.ARS-UI_Ramb_v2.0.dna.toplevel.fa \
  --output results/ERR10859992 \
  --threads 8 \
  --nvrna
Starting correct...
Flair correct took 5 minutes and 6 seconds

Flair took 5 minutes and 6 seconds and finished without issues.

FLAIR HAS FINISHED
```
