### ISSUE TITLE
Flair collapse does not support .fa.gz

### ISSUE THREAD

**Issue by vpeddu** [BrooksLabUCSC/flair#359]
**Copy and paste the exact command you tried to run**
(flair) vpeddu@crimson:/private/groups/kimlab/vikas/$ flair collapse -g hs1.fa.gz -q flair.correct_all_corrected.bed -r <fq1> <fq2> <fq3> --generate_map --threads 16 --gtf gencode.v39.annotation.gtf --output flair.collapse

**How did you install Flair?**
Conda

Flair collapse does not support .fa.gz while correct/align do. 

```
Writing temporary files to /data/tmp/tmpe_8chksy/
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Renaming isoforms using gtf
Traceback (most recent call last):
  File "/private/groups/kimlab/vikas/miniconda/envs/flair/lib/python3.10/site-packages/flair/bed_to_sequence.py", line 253, in <module>
    for line in open(args.genome):
  File "/private/groups/kimlab/vikas/miniconda/envs/flair/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**What else do we need to know?**
Same command works when I unzip the fasta and provide that

**Comment by cafelton** [comment]
Related to #374

**Comment by brandon-hastings** [comment]
Same for me. `bed_to_sequence` does not support a gzipped fasta while the preceding functions did. Solved when unzipping the fasta file before `flair collapse`

**Comment by diekhans** [comment]
Weneed to support compressed fastas everywhere

**Comment by cafelton** [comment]
Tested, align, collapse, and quantify all support compressed fasta/fastq now
