### ISSUE TITLE
Flair collapse path issues on EasyBuild install. 

### ISSUE THREAD

**Issue by srbennett** [BrooksLabUCSC/flair#365]
**Copy and paste the exact command you tried to run**
flair collapse \
--threads 18 \
--stringent --check_splice --generate_map --annotation_reliant generate \
--genome /Sean/Salmon/Human_Ref_Gencode_R45/GRCh38.primary_assembly.genome.fa \
--gtf /Sean/Salmon/Human_Ref_Gencode_R45/gencode.v45.primary_assembly.annotation.gtf \
-q /Sean/Flair_Gizmo/Single_Sample/MB135_iDUX4ca_NoDox_Flair_SingleSample_FlairCorrect_all_corrected.bed \
-r /user/sbennett/PacBio_Kinnex_MB135_iDUX4/Flair/fastqs/MB135_iDUX4ca_NoDox_flnc.fastq.gz \
--output /Sean/Flair_Gizmo/Single_Sample/Annot_Reliant_Collapse/MB135_iDUX4ca_NoDox_Flair_SingleSample_FlairCorrect_FlairCollapse

**How did you install Flair?**
(We'd prefer it if you used one of the top two because they are the least likely to have package compatibility problems.)
Built my my scicomp group for cluster usage using EasyBuild using bioconda

**What happened?**
Note: Pathing information second hand from SciComp developer helping troubleshoot install.

flair collapse is unable to access required accessory functions count_sam_transcripts.py and collapse_isoforms_precise.py due to a quirk with python expecting file paths to be passed via PYTHONPATH while pipettor's subprocess.Popen() uses PATH. 

Failure manifests in two ways:
1. If /lib/python3.11/site-packages/flair is not in path, flair collapse fails with a no such file/directory error.
2. If you add /lib/python3.11/site-packages/flair to PATH you get a permission denied error, as things in the site-packages directory don't have the +x bit set. 
```
Failure mode 1:
Starting collapse...
Traceback (most recent call last):
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 146, in _start_process
    self.popen = subprocess.Popen(self.cmd,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/app/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'collapse_isoforms_precise.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/software/FLAIR/2.0-foss-2023a/bin/flair", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/flair/flair.py", line 51, in main
    [isoforms, isoform_sequences] = collapse()
                                    ^^^^^^^^^^
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/flair/flair_collapse.py", line 345, in collapse
    pipettor.run([collapse_cmd])
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/__init__.py", line 32, in run
    Pipeline(cmds, stdin=stdin, stdout=stdout, stderr=stderr, logger=logger, logLevel=logLevel).wait()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 471, in wait
    self._wait_guts()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 455, in _wait_guts
    self.start()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 417, in start
    self._start_guts()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 405, in _start_guts
    self._start_processes()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 362, in _start_processes
    self._start_process(proc)
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 357, in _start_process
    proc._start()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 162, in _start
    raise self.procExcept
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 158, in _start
    self._start_process()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 151, in _start_process
    raise ProcessException(str(self)) from ex
pipettor.exceptions.ProcessException: exec failed: collapse_isoforms_precise.py -q /fh/scratch/delete90/tapscott_s/Sean/Flair_Gizmo/Single_Sample/MB135_iDUX4ca_NoDox_Flair_SingleSample_FlairCorrect_all_corrected.bed -t 18 -m 2 -w 100 -n none -o /fh/scratch/delete90/tapscott_s/Sean/Flair_Gizmo/Single_Sample/Annot_Reliant_Collapse/MB135_iDUX4ca_NoDox_Flair_SingleSample_FlairCorrect_FlairCollapse_NoArgs.firstpass.unfiltered.bed -f /fh/scratch/delete90/tapscott_s/Sean/Salmon/Human_Ref_Gencode_R45/gencode.v45.primary_assembly.annotation.gtf


Failure mode 2:
Starting collapse...
Writing temporary files to /loc/scratch/60241883/tmplrmx1tw7/	
Making transcript fasta using annotated gtf and genome sequence
Aligning reads to reference transcripts
Counting supporting reads for annotated transcripts
Setting up unassigned reads for flair-collapse novel isoform detection
Traceback (most recent call last):
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 146, in _start_process
    self.popen = subprocess.Popen(self.cmd,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/app/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'collapse_isoforms_precise.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/software/FLAIR/2.0-foss-2023a/bin/flair", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/flair/flair.py", line 51, in main
    [isoforms, isoform_sequences] = collapse()
                                    ^^^^^^^^^^
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/flair/flair_collapse.py", line 345, in collapse
    pipettor.run([collapse_cmd])
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/__init__.py", line 32, in run
    Pipeline(cmds, stdin=stdin, stdout=stdout, stderr=stderr, logger=logger, logLevel=logLevel).wait()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 471, in wait
    self._wait_guts()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 455, in _wait_guts
    self.start()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 417, in start
    self._start_guts()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 405, in _start_guts
    self._start_processes()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 362, in _start_processes
    self._start_process(proc)
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 357, in _start_process
    proc._start()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 162, in _start
    raise self.procExcept
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 158, in _start
    self._start_process()
  File "/app/software/FLAIR/2.0-foss-2023a/lib/python3.11/site-packages/pipettor/processes.py", line 151, in _start_process
    raise ProcessException(str(self)) from ex
pipettor.exceptions.ProcessException: exec failed: collapse_isoforms_precise.py -q /fh/scratch/delete90/tapscott_s/Sean/Flair_Gizmo/Single_Sample/Annot_Reliant_Collapse/MB135_iDUX4ca_NoDox_Flair_SingleSample_FlairCorrect_FlairCollapse.unassigned.bed -t 18 -m 2 -w 100 -n none -o /fh/scratch/delete90/tapscott_s/Sean/Flair_Gizmo/Single_Sample/Annot_Reliant_Collapse/MB135_iDUX4ca_NoDox_Flair_SingleSample_FlairCorrect_FlairCollapse.firstpass.unfiltered.bed -f /fh/scratch/delete90/tapscott_s/Sean/Salmon/Human_Ref_Gencode_R45/gencode.v45.primary_assembly.annotation.gtf
```

**What else do we need to know?**

This is likely a weird interaction between how EasyBuild builds stuff on our cluster and Flair and may be incorrect due to my misunderstanding the developer helping me navigate the install. Happy to clarify anything that doesn't make sense.

**Comment by diekhans** [comment]
We could set PAHT internally to flair, but I think a better way (as in more obvious) is to call python directly and pass the internal script as an argument.

**Comment by alexdhill** [comment]
I came across this same issue in a docker container, where flair itself seems to want the `src/flair` directory mounted to the path as opposed to the `bin`.

**Comment by Prakrithi-P** [comment]
Hi, 
  Any idea on how exactly to solve this? I have all paths set but still face the same issue.

Thanks,
Prakrithi
