### ISSUE TITLE
flair collapse crashes on MacOS

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#367]
flair collapse crashes with  `TypeError: 'NoneType' object is not subscriptable` on python 3.8 and beyond.

This is because MacOS no longer uses the multiprocessing fork server by default. This is because it is not safe with some MacOS libraries. Flavor might actually work okay with the fork server due to the limited number of external codes used.

However, the fork server is is out of favor for similar problems with threads on linux as well.  It would be go to switch to the spawn server for all platforms.  However, that means sending data to the subprocesses rather than just having it there due to the fork.

see [Contexts and start methods](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)

```
Starting collapse...
Writing temporary files to /var/folders/gz/rw4d00bs3s1dtp28z0vh827r0000gn/T/tmpb2vp55x8/	
Making transcript fasta using annotated gtf and genome sequence
Aligning reads to reference transcripts
Counting supporting reads for annotated transcripts
Setting up unassigned reads for flair-collapse novel isoform detection
Traceback (most recent call last):
  File "/Users/markd/compbio/flair/projs/src/flair-markd//bin/flair", line 86, in <module>
    main()
  File "/Users/markd/compbio/flair/projs/src/flair-markd//bin/flair", line 51, in main
    [isoforms, isoform_sequences] = collapse()
  File "/Users/markd/compbio/flair/projs/src/flair-markd/src/flair/flair_collapse.py", line 345, in collapse
    pipettor.run([collapse_cmd])
  File "/Users/markd/compbio/flair/projs/bug-fixes/miniconda3/envs/flair/lib/python3.8/site-packages/pipettor/__init__.py", line 32, in run
    Pipeline(cmds, stdin=stdin, stdout=stdout, stderr=stderr, logger=logger, logLevel=logLevel).wait()
  File "/Users/markd/compbio/flair/projs/bug-fixes/miniconda3/envs/flair/lib/python3.8/site-packages/pipettor/processes.py", line 471, in wait
    self._wait_guts()
  File "/Users/markd/compbio/flair/projs/bug-fixes/miniconda3/envs/flair/lib/python3.8/site-packages/pipettor/processes.py", line 464, in _wait_guts
    self._raise_if_failed()
  File "/Users/markd/compbio/flair/projs/bug-fixes/miniconda3/envs/flair/lib/python3.8/site-packages/pipettor/processes.py", line 427, in _raise_if_failed
    raise ex
  File "/Users/markd/compbio/flair/projs/bug-fixes/miniconda3/envs/flair/lib/python3.8/site-packages/pipettor/processes.py", line 424, in _raise_if_failed
    raise p.procExcept
pipettor.exceptions.ProcessException: process exited 1: collapse_isoforms_precise.py -q output/combined_samples.flair.collapse.unassigned.bed -t 4 -m 2 -w 100 -n none -o output/combined_samples.flair.collapse.firstpass.unfiltered.bed -f ./reference/hg38_chr22.gtf:
Annotated ends extracted from GTF
Read data extracted
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/markd/compbio/flair/projs/bug-fixes/miniconda3/envs/flair/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/markd/compbio/flair/projs/bug-fixes/miniconda3/envs/flair/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/markd/compbio/flair/projs/src/flair-markd/src/flair/collapse_isoforms_precise.py", line 248, in run_iterative_add_se
    se_ordered = all_se_by_chrom[chrom].keys()
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/markd/compbio/flair/projs/src/flair-markd//src/flair/collapse_isoforms_precise.py", line 698, in <module>
    res = p.map(run_iterative_add_se, chrom_names)
  File "/Users/markd/compbio/flair/projs/bug-fixes/miniconda3/envs/flair/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/markd/compbio/flair/projs/bug-fixes/miniconda3/envs/flair/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing

```

**Comment by diekhans** [comment]
Fixed in master; should test on MacOS before release.
