### ISSUE TITLE
Error :: gtf_to_bed.py", line 108, in <module>

### ISSUE THREAD

**Issue by shin0727** [BrooksLabUCSC/flair#386]
**Copy and paste the exact command you tried to run**
Feel free to leave any original paths, we don't have access to your system

**How did you install Flair?**
(We'd prefer it if you used one of the top two because they are the least likely to have package compatibility problems.)
1. bioconda (e.g. `conda create -n flair -c conda-forge -c bioconda flair`)

**What happened?**
Error during "Making transcript fasta using annotated gtf and genome sequence"
```
Writing temporary files to /tmp/tmpy5hutmlp/
Making transcript fasta using annotated gtf and genome sequence
Traceback (most recent call last):
  File "tools/miniconda3/envs/flair/lib/python3.10/site-packages/flair/gtf_to_bed.py", line 108, in <module>
    if blockcount > 1 and blockstarts[0] > blockstarts[1]:  # need to reverse exons
IndexError: list index out of range
Traceback (most recent call last):
  File "tools/miniconda3/envs/flair/bin/flair", line 10, in <module>
    sys.exit(main())
  File "tools/miniconda3/envs/flair/lib/python3.10/site-packages/flair/flair.py", line 1035, in main
    status = collapse()
  File "tools/miniconda3/envs/flair/lib/python3.10/site-packages/flair/flair.py", line 522, in collapse
    subprocess.check_call([sys.executable, path+'gtf_to_bed.py', args.f, args.annotated_bed, '--include_gene'])
  File "tools/miniconda3/envs/flair/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tools/miniconda3/envs/flair/bin/python', 'tools/miniconda3/envs/flair/lib/python3.10/site-packages/flair/gtf_to_bed.py', '/home/jwshin0727/Project/240926_IBS_Bat/09_geneAnnotation/05_egapx/7_Mm_scaf/complete.genomic.mod.gtf', '7_Mm_scaf.annotated_transcripts.bed', '--include_gene']' returned non-zero exit status 1.
```

I used a GTF file generated by "egapx" as input. While the process works fine for other samples, this specific sample is causing an error. I'm not sure what is causing the issue or how to resolve it.

Can anyone provide assistance?

**Comment by diekhans** [comment]
this looks like a problem in the GTF.  if you print the variable line right before if blockcount > 1 and blockstarts[0] > blockstarts[1] you should be able to see what GTF record is causing this

**Comment by shin0727** [comment]
Thank you for your response.

As you mentioned, I printed the problematic GTF line, and here is the result:

```
(flair) jwshin0727@node200:~/Project/240926_IBS_Bat/09_geneAnnotation/03_flair/03_collapse/7_Mm_scaf$ python gtf_to_bed.py complete.genomic.mod.gtf ll.bed
**Processing line: ['h1tg001773l', 'Gnomon', 'stop_codon', '45093', '45095', '.', '+', '0', 'gene_id "egapxtmp_017728"; transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; gbkey "CDS"; locus_tag "egapxtmp_017728"; orig_transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; product "DNA-directed RNA polymerase II subunit GRINL1A-like"; protein_id "WGS:ZZZZ:egapxtmp_017728-P1"; exon_number "1";']**
Traceback (most recent call last):
  File "/home/jwshin0727/Project/240926_IBS_Bat/09_geneAnnotation/03_flair/03_collapse/7_Mm_scaf/gtf_to_bed.py", line 109, in <module>
    if blockcount > 1 and blockstarts[0] > blockstarts[1]:  # need to reverse exons
IndexError: list index out of range

```

However, I don’t understand why this record is causing the error. 

When I checked the genome’s `.fai` file, the size of the corresponding contig is 50,425 bp, and the transcript does not exceed the contig’s length. 

I’d like to know the reason for this issue.

**Comment by shin0727** [comment]
When I remove the "egapxtmp_017728" associated line in input gtf file, the flair collapse seems to work well. But is there any solution, without removing records from the gtf??

**Comment by diekhans** [comment]
Can you attach all the GFF lines associated with problem transcript?

**Comment by shin0727** [comment]
Here's the problem transcript from gtf
```
h1tg001773l	Gnomon	gene	44169	45095	.	+	.	gene_id "egapxtmp_017728"; transcript_id ""; description "DNA-directed RNA polymerase II subunit GRINL1A-like"; gbkey "Gene"; gene_biotype "protein_coding"; locus_tag "egapxtmp_017728"; 
h1tg001773l	Gnomon	transcript	44169	45095	.	+	.	gene_id "egapxtmp_017728"; transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; gbkey "mRNA"; locus_tag "egapxtmp_017728"; model_evidence "Supporting evidence includes similarity to: 5 Proteins"; orig_protein_id "gnl|WGS:ZZZZ|egapxtmp_017728-P1"; orig_transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; product "DNA-directed RNA polymerase II subunit GRINL1A-like"; transcript_biotype "mRNA"; 
h1tg001773l	Gnomon	exon	44169	45095	.	+	.	gene_id "egapxtmp_017728"; transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; locus_tag "egapxtmp_017728"; model_evidence "Supporting evidence includes similarity to: 5 Proteins"; orig_protein_id "gnl|WGS:ZZZZ|egapxtmp_017728-P1"; orig_transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; product "DNA-directed RNA polymerase II subunit GRINL1A-like"; transcript_biotype "mRNA"; exon_number "1"; 
h1tg001773l	Gnomon	CDS	44313	45092	.	+	0	gene_id "egapxtmp_017728"; transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; gbkey "CDS"; locus_tag "egapxtmp_017728"; orig_transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; product "DNA-directed RNA polymerase II subunit GRINL1A-like"; protein_id "WGS:ZZZZ:egapxtmp_017728-P1"; exon_number "1"; 
h1tg001773l	Gnomon	start_codon	44313	44315	.	+	0	gene_id "egapxtmp_017728"; transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; gbkey "CDS"; locus_tag "egapxtmp_017728"; orig_transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; product "DNA-directed RNA polymerase II subunit GRINL1A-like"; protein_id "WGS:ZZZZ:egapxtmp_017728-P1"; exon_number "1"; 
h1tg001773l	Gnomon	stop_codon	45093	45095	.	+	0	gene_id "egapxtmp_017728"; transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; gbkey "CDS"; locus_tag "egapxtmp_017728"; orig_transcript_id "gnl|WGS:ZZZZ|egapxtmp_017728-R1"; product "DNA-directed RNA polymerase II subunit GRINL1A-like"; protein_id "WGS:ZZZZ:egapxtmp_017728-P1"; exon_number "1"; 

```

Here's the problem transcript line in gff
```
h1tg001773l	Gnomon	gene	44169	45095	.	+	.	ID=gene-egapxtmp_017728;Name=egapxtmp_017728;description=DNA-directed RNA polymerase II subunit GRINL1A-like;gbkey=Gene;gene_biotype=protein_coding;locus_tag=egapxtmp_017728
h1tg001773l	Gnomon	mRNA	44169	45095	.	+	.	ID=rna-gnl|WGS:ZZZZ|egapxtmp_017728-R1;Parent=gene-egapxtmp_017728;gbkey=mRNA;locus_tag=egapxtmp_017728;model_evidence=Supporting evidence includes similarity to: 5 Proteins;orig_protein_id=gnl|WGS:ZZZZ|egapxtmp_017728-P1;orig_transcript_id=gnl|WGS:ZZZZ|egapxtmp_017728-R1;product=DNA-directed RNA polymerase II subunit GRINL1A-like
h1tg001773l	Gnomon	exon	44169	45095	.	+	.	ID=exon-gnl|WGS:ZZZZ|egapxtmp_017728-R1-1;Parent=rna-gnl|WGS:ZZZZ|egapxtmp_017728-R1;gbkey=mRNA;locus_tag=egapxtmp_017728;orig_protein_id=gnl|WGS:ZZZZ|egapxtmp_017728-P1;orig_transcript_id=gnl|WGS:ZZZZ|egapxtmp_017728-R1;product=DNA-directed RNA polymerase II subunit GRINL1A-like
h1tg001773l	Gnomon	CDS	44313	45095	.	+	0	ID=cds-egapxtmp_017728;Parent=rna-gnl|WGS:ZZZZ|egapxtmp_017728-R1;Name=WGS:ZZZZ:egapxtmp_017728-P1;gbkey=CDS;locus_tag=egapxtmp_017728;orig_transcript_id=gnl|WGS:ZZZZ|egapxtmp_017728-R1;product=DNA-directed RNA polymerase II subunit GRINL1A-like;protein_id=WGS:ZZZZ:egapxtmp_017728-P1

```

**Comment by diekhans** [comment]
One problem is that FLAIR fails if only one transcript is in a file. So testing with your GTF subset doesn't test the problem you are having.

Can you add our full GTF (compressed) to this ticket?

**Comment by shin0727** [comment]
> One problem is that FLAIR fails if only one transcript is in a file. So testing with your GTF subset doesn't test the problem you are having.
> 
> Can you add our full GTF (compressed) to this ticket?

[Uploading complete.genomic.gtf.gz…]()

**Comment by diekhans** [comment]
Replacing src/flair/gtf_to_bed.py with the updated version linked here, it should fix the problem.

https://raw.githubusercontent.com/BrooksLabUCSC/flair/refs/heads/master/src/flair/gtf_to_bed.py

**Comment by shin0727** [comment]
Dear @diekhans 
Thank your for the solution.
I will try it, and then tell you whether it works well.

Thank you again!!!

**Comment by shin0727** [comment]
Dear @diekhans,
It works well without errors.
I will close the issue. thank you

**Comment by shin0727** [comment]
I worked well with new script.
