### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable - Flair collapse

### ISSUE THREAD

**Issue by XieLab-VSU** [BrooksLabUCSC/flair#390]
**Copy and paste the exact command you tried to run**
```
flair collapse -g /Volumes/Marone_VSU/Cancer_Project/RNA_Seq/GRCh38_GENCODE_ref/Reference_files/gencode.v47.GRCh38.primary_assembly.genome.fa --gtf /Volumes/Marone_VSU/Cancer_Project/RNA_Seq/GRCh38_GENCODE_ref/Reference_files/gencode.v47.primary_assembly.annotation.gtf -q concat_corrected.bed -r /Volumes/Marone_VSU/Cancer_Project/RNA_Seq/Direct_RNA_Seq/FHC_VEH_A_DirRNASeq/basecalls/FHC_VEH_A_filtered.fastq.gz /Volumes/Marone_VSU/Cancer_Project/RNA_Seq/Direct_RNA_Seq/FHC_VEH_B_DirRNASeq/basecalls/FHC_VEH_B_filtered.fastq.gz /Volumes/Marone_VSU/Cancer_Project/RNA_Seq/Direct_RNA_Seq/FHC_PHIP_A_DirRNASeq/basecalls/FHC_PHIP_A_filtered.fastq.gz /Volumes/Marone_VSU/Cancer_Project/RNA_Seq/Direct_RNA_Seq/FHC_PHIP_B_DirRNASeq/basecalls/FHC_PHIP_B_filtered.fastq.gz --stringent --check_splice --generate_map --annotation_reliant generate --output flair-collapse/

```

**How did you install Flair?**

conda create -n FLAIR -c conda-forge -c bioconda flair

**What happened?**

```
Writing temporary files to /var/folders/p4/8wsv664j0438m1y1rwptd4bh0000gn/T/tmpoq9o699t/	
Making transcript fasta using annotated gtf and genome sequence
Aligning reads to reference transcripts
Counting supporting reads for annotated transcripts
Setting up unassigned reads for flair-collapse novel isoform detection
Annotated ends extracted from GTF
Read data extracted
Annotated ends extracted from GTF
Annotated ends extracted from GTF
Annotated ends extracted from GTF
Annotated ends extracted from GTF
Read data extracted
Read data extracted
Read data extracted
Read data extracted
Single-exon genes grouped, collapsing
Single-exon genes grouped, collapsing
Single-exon genes grouped, collapsing
Single-exon genes grouped, collapsing
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/michael/miniforge3/envs/FLAIR/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/michael/miniforge3/envs/FLAIR/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/michael/miniforge3/envs/FLAIR/lib/python3.8/site-packages/flair/collapse_isoforms_precise.py", line 236, in run_iterative_add_se
    se_ordered = all_se_by_chrom[chrom].keys()
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/michael/miniforge3/envs/FLAIR/lib/python3.8/site-packages/flair/collapse_isoforms_precise.py", line 682, in <module>
    res = p.map(run_iterative_add_se, chrom_names)
  File "/Users/michael/miniforge3/envs/FLAIR/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/michael/miniforge3/envs/FLAIR/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable
```

**What else do we need to know?**
Here is the head of my concatenated bed file. 
```
(FLAIR) Michaels-MacBook-Pro-3:flair-correct-beds michael$ head concat_corrected.bed 
GL000008.2	66710	67120	3cd1717e-6c04-461e-92ea-cb29647e0c40	0	-	66710	67120	255,0,0	1	410,	0,
GL000008.2	132846	135290	5ac06aac-a1fd-4a13-9f56-76b0ff1dcf94	0	+	132846	135290	255,0,0	1	2444,	0,
GL000008.2	134352	135319	18abf9b9-ae86-4a09-b1cc-affeddcd7983	0	+	134352	135319	255,0,0	1	967,	0,
GL000008.2	151499	152841	4f1f2da2-1234-4d05-a168-9cd89e697c54	0	-	151499	152841	255,0,0	1	1342,	0,
GL000008.2	151499	155785	66222108-2401-49c1-8f0e-bebd7c70c20f	16	-	151499	155785	255,0,0	1	4286,	0,
GL000008.2	151520	152922	799870dc-bf56-4540-b4d1-d2a53a6fba87	0	-	151520	152922	255,0,0	1	1402,	0,
GL000008.2	151524	152957	2d25c5f1-0a2a-4834-add3-fb5b15543273	0	-	151524	152957	255,0,0	1	1433,	0,
GL000008.2	151972	152847	328b107e-26db-49a2-9a0e-a81f75859936	0	-	151972	152847	255,0,0	1	875,	0,
GL000008.2	151972	152984	7876287e-4cf6-4678-b32f-b1bdc97ac84c	0	-	151972	152984	255,0,0	1	1012,	0,
GL000008.2	151972	153077	aa157ec1-083c-4407-865d-e73a75fbb4e6	0	-	151972	153077	255,0,0	1	1105,	0,
```
Go ahead, every bit helps.

**Comment by cafelton** [comment]
Related to #392

**Comment by diekhans** [comment]
This issue is related to the handling of single-exon transcripts.  We are working on adding test cases for SE transcripts.
