### ISSUE TITLE
Error script of conda version

### ISSUE THREAD

**Issue by liuxiawei** [BrooksLabUCSC/flair#398]
**Copy and paste the exact command you tried to run**
```
 flair collapse   -g /hg38/hg38.fa --gtf /hg38/hg38.ncbiRefSeq_reformatted_clean_chr.gtf  --threads 48 -q /co/qqq/results/7_sqanti3/4_flair/293t-1/293t-1_all_corrected.bed --output /co/qqq/results/7_sqanti3/4_flair/293t-1/isoforms -r /co/qqq/results/7_sqanti3/1_pychopper/293t-1.lr.fq --stringent --check_splice --generate_map --annotation_reliant generate --keep_intermediate --temp_dir /tmp/flair_collapse
```
**How did you install Flair?**
1. bioconda (e.g. `conda create -n flair -c conda-forge -c bioconda flair`)

**What happened?**
I used flair and faced the error:
```
(74296813, 74296988)
Entry name should contain underscore-delimited transcriptid and geneid like so:		 ENST00000318842.11_ENSG00000156313.12 or a4bab8a3-1d28_chr8:232000
So no GTF conversion was done. Please run identify_gene_isoform first
for best results, or run with --force
Traceback (most recent call last):
  File "/micromamba/bin/flair", line 10, in <module>
    sys.exit(main())
  File "/micromamba/lib/python3.9/site-packages/flair/flair.py", line 1035, in main
    status = collapse()
  File "/micromamba/lib/python3.9/site-packages/flair/flair.py", line 663, in collapse
    subprocess.check_call([sys.executable, path+'bed_to_gtf.py', args.o+'isoforms.bed'],
  File "/micromamba/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/micromamba/bin/python', '/micromamba/lib/python3.9/site-packages/flair/bed_to_gtf.py', '/co/qqq/results/7_sqanti3/4_flair/293t-1/isoforms.isoforms.bed']' returned non-zero exit status 1.
```
The line `(74296813, 74296988)` was I debug by `print(name)` in `bed_to_gtf.py` . I found the newest version of conda package is still consider only "psl" as bed file while I really pass the `bed` file.  I think this script is forgot to update with git. I would try to renew the script and report

**Comment by liuxiawei** [comment]
Finally I found the error caused by inconsistency of `sam` file and `gtf`. The `gtf` removed some chromosome while the `fasta` is still. And the removed chromosome is existed in `bam`. So that the error bed is failed to gtf .
