### ISSUE TITLE
Error at diff-exp - rpy2 error 

### ISSUE THREAD

**Issue by basicallydean** [BrooksLabUCSC/flair#76]
Hey guys, 

I'm having a go at running the diffexp module, but I'm coming up against this error. 

running DESEQ2 dge
Traceback (most recent call last):
  File "/home/labpc/Bioinformatics-Programs/flair/bin/runDE.py", line 218, in <module>
    main()
  File "/home/labpc/Bioinformatics-Programs/flair/bin/runDE.py", line 110, in main
    df = pandas2ri.py2ri(quantDF)
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'

Could you guys please list the exact version of each program/package that you's used in which flair-diffexp was last functional? 

Many thanks,
Dean

**Comment by basicallydean** [comment]
Just realised this is in misc - will reinstall and try again
