### ISSUE TITLE
Error in correct

### ISSUE THREAD

**Issue by csijcs** [BrooksLabUCSC/flair#8]
Hello,

I'm trying to run this pipeline with data I've previously aligned and getting an error. I have created the bed12 file and when I run:

`python ~/flair/flair.py correct -f /data2/csijcs/hg38/gencode.v29.annotation.gtf -c /data2/csijcs/hg38/hg38.chrom.sizes -q /data2/csijcs/nanopore/AML_009_combined/AML_009_combined_sorted.bed`

I get the following error:

`Traceback (most recent call last):
  File "/home/csijcs/flair/bin/ssPrep.py", line 21, in <module>
  File "/home/csijcs/flair/bin/ssPrep.py", line 21, in <module>
        from kerneltree import IntervalTree
ImportError: No module named kerneltree
from kerneltree import IntervalTree
ImportError: No module named kerneltree`

Can you tell me what's going wrong here?

Thanks,
J

**Comment by csijcs** [comment]
I'm sorry, nevermind. Technical glitch. I had installed kerneltree, but apparently I think I had to close and restart my session. Working now.
